### PR TITLE
More font size choices and line spacing options

### PR DESCRIPTION
**Pull request by Shedimus**
I've added a line spacing option/modifier for when you've got too many references you need to squish down. Also added a range of font size choices, all as the standard latex font size choices. I think being able to specify pt size for sections might be useful. 

I've left the default memoir class option in, but the options are very limited and solutions seem very fragile. The next lowest option from 30pt is 25pt for example (too small in my opinion).

Thanks for making this package by the way, forced me to learn latex finally!

### CODE REVIEW

**Comment by brentthorne** [comment]
Hello @Shedimus thanks again for your work! I like the implementation for line spacing and the options you have added for sizing of each major text option. Bellow is a short list of the changes this pull request would need for me to merge and some explanation as as well! 

LateX in general is fairly strict with font sizing as the fonts available are often unable to adjust. The Memoir and Koma document classes provide the most (12) sizing options available based on the initial size chosen. **[Here](http://www.sascha-frank.com/latex-font-size.html)** is a good resource for seeing how it works. If you go to the table for the Memoir class in that post you will see how the initial size option or the `command` row is chosen and from there the rest of the sizing changes. 

I would like to keep the option to set the overall font size of the document ie `font_size: "30pt"` -> `\documentclass[article,$font_size$,extrafontsizes]{memoir}`. While it is frustrating it is still the best option in my mind for keeping things as simple as possible for non LateX users. This way they know the body text will be set to a specific size and that they can adjust the rest accordingly based on the corresponding `\huge` or `\Huge` or even `\HUGE` as offered by memoir. 

Because there isn't a pull request submission guide I'll tell you what I think may need changed to merge, If you are okay doing it that's great, if not then I can merge this sometime later this week when I have time to make the changes I mention here myself.

- [ ] return the `.Tex` file document class to `\documentclass[article,$font_size$,extrafontsizes]{memoir}`
- [ ] use consistent naming for YAML options. If you look at the **Text Colour** section of the YAML you will see how I started this. Just replace `col` with `size` and that should work great! 
- [ ]  Finally , add your name to the `.Tex` file at the top as a contributor and feel free to initial with a comment any spot where you made changes to it. This way you get credit plus when I come back to the document I can know who has added what when I go to make any updates!

Thanks again!

**Comment by Shedimus** [comment]
Hi @brentthorne, thanks for such detailed feedback, especially the info about font sizes. 

Happy to make the changes necessary for the merge, I should have been more thorough before the pull request, especially with the ReadMe! 
I'll make them soon and then re-commit to this PR if that's ok with you?

**Comment by brentthorne** [comment]
@Shedimus that works for me! 

No worries about the initial PR, there is no PR Protocol for this repo yet so its basically a free for all right now until I get that together :unamused: .

Take however much time you need to make those changes! :tada:

**Comment by Shedimus** [comment]
I think it _should_ be acceptable for merging now, there's actually ReadMe entries now for my changes:
> * [x]  return the `.Tex` file document class to `\documentclass[article,$font_size$,extrafontsizes]{memoir}`
> * [x]  use consistent naming for YAML options. If you look at the **Text Colour** section of the YAML you will see how I started this. Just replace `col` with `size` and that should work great!
> * [x]  Any additions to the YAML would also require additions to the [ReadMe YAML table](https://github.com/brentthorne/posterdown#yaml-options) with a description of each new addition.
> * [x]   Finally , add your name to the `.Tex` file at the top as a contributor and feel free to initial with a comment any spot where you made changes to it. This way you get credit plus when I come back to the document I can know who has added what when I go to make any updates!

I ended up returning the document class in an earlier commit anyway so that wasn't required this time around.  Let me know if you need anything else before merging! 🎉

**Comment by brentthorne** [comment]
This looks good to me! Thanks for the help :smiley:

**Pull request merged**
